# Generated by Django 3.1 on 2020-09-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_commentthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_thread',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.commentthread'),
        ),
    ]
